name: PlatformIO CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install PlatformIO
      run: pip install platformio

    - name: Update PlatformIO
      run: pio platform update

    - name: Build for all environments
      run: pio run

    - name: Run Unit Tests
      run: pio test
